# Generated by Django 6.0.6 on 2026-07-07 10:41

import attestations.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Développement Web (HTML, CSS, JavaScript)', max_length=200, unique=True, verbose_name='Intitulé de la formation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_attestation', models.CharField(blank=True, help_text="Généré automatiquement à l'enregistrement (ex : WA-2026-S1-014-7X2K).", max_length=40, unique=True, verbose_name="Numéro d'attestation")),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début de la formation')),
                ('date_fin', models.DateField(verbose_name='Date de fin de la formation')),
                ('volume_horaire', models.PositiveIntegerField(verbose_name='Volume horaire (heures)')),
                ('date_delivrance', models.DateField(default=django.utils.timezone.now, verbose_name="Date de délivrance de l'attestation")),
                ('annee_session', models.PositiveIntegerField(default=attestations.models.annee_courante, verbose_name='Année de la session')),
                ('numero_session', models.PositiveIntegerField(default=1, help_text='Ex : 1 pour la 1ère session (deviendra S1 dans le numéro).', verbose_name='Numéro de session')),
                ('session_label', models.CharField(blank=True, help_text='Ex : Session 1 - Vogan', max_length=150, verbose_name='Nom de la session')),
                ('statut', models.CharField(choices=[('Valide', 'Valide'), ('Revoquee', 'Révoquée')], default='Valide', max_length=20, verbose_name='Statut')),
                ('afficher_nom_complet', models.BooleanField(default=False, help_text="Cocher uniquement si l'apprenant a donné son accord écrit pour l'affichage de son nom complet. Sinon, seule l'initiale du nom sera affichée.", verbose_name='Afficher le nom complet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='attestations.formation', verbose_name='Formation suivie')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ['-date_delivrance', '-id'],
            },
        ),
    ]
