# Generated by Django 6.0.7 on 2026-07-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_etudiant_attestations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('qcm', 'Choix multiples (QCM)'), ('vf', 'Vrai / Faux'), ('courte', 'Réponse courte')], default='qcm', max_length=10, verbose_name='Type de question')),
                ('enonce', models.TextField(verbose_name='Énoncé de la question')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('consignes', models.TextField(blank=True, help_text='Instructions générales affichées en haut du sujet (optionnel).', verbose_name='Consignes')),
                ('duree_minutes', models.PositiveIntegerField(help_text="Temps laissé à l'apprenant à partir du moment où il ouvre le sujet.", verbose_name='Durée accordée (en minutes)')),
                ('actif', models.BooleanField(default=False, help_text='Décoche pour cacher le sujet pendant que tu le prépares.', verbose_name='Visible par les apprenants')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Sujet',
                'verbose_name_plural': 'Sujets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('terminee', models.BooleanField(default=False, verbose_name='Corrigée / terminée')),
                ('note_obtenue', models.FloatField(blank=True, null=True, verbose_name='Note obtenue')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='comptes.etudiant', verbose_name='Apprenant')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='examens.sujet', verbose_name='Sujet')),
            ],
            options={
                'verbose_name': 'Copie',
                'verbose_name_plural': 'Copies',
                'ordering': ['-date_debut'],
                'unique_together': {('sujet', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255, verbose_name="Texte de l'option")),
                ('est_correct', models.BooleanField(default=False, verbose_name="C'est une bonne réponse")),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_possibles', to='examens.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseAcceptee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(help_text='La comparaison ignore les majuscules/minuscules et les espaces en trop.', max_length=255, verbose_name='Réponse acceptée')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_acceptees', to='examens.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse acceptée',
                'verbose_name_plural': 'Réponses acceptées',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examens.sujet', verbose_name='Sujet'),
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_libre', models.TextField(blank=True, verbose_name='Réponse libre')),
                ('points_obtenus', models.FloatField(default=0, verbose_name='Points obtenus')),
                ('choix_selectionnes', models.ManyToManyField(blank=True, to='examens.choix', verbose_name='Choix sélectionné(s)')),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='examens.copie', verbose_name='Copie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etudiants', to='examens.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': "Réponse d'apprenant",
                'verbose_name_plural': "Réponses d'apprenants",
                'unique_together': {('copie', 'question')},
            },
        ),
    ]
