# Generated by Django 6.0.7 on 2026-07-14 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_etudiant_attestations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_dernier_message', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernier message le')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_ia', to='comptes.etudiant', verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': "Conversation avec l'assistant IA",
                'verbose_name_plural': "Conversations avec l'assistant IA",
                'ordering': ['-date_dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Apprenant'), ('ia', 'Assistant IA')], max_length=10, verbose_name='Auteur')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['date_envoi'],
            },
        ),
    ]
